import {
  PlayerCurrentHex,
  PlayerVisitedHexes,
} from "../MapData/PlayerDataLists"
import {
  RockyTerrain,
  Chasm,
  Lava,
  Tundra,
  Water,
  Weird,
  Forest,
  Sand,
  VisibleWaterList,
  BorderOceans,
} from "../MapData/Terrain"
import {
  PointsOfInterest,
  RestStops,
  Towers,
  Tombs,
} from "../MapData/Locations"
import { findNearbyKeysFactory } from "../utils/findNearbyKeysFactory"
import { HexConfigLookup } from "../types"

export type MapDataState = {
  players: {
    current: string
    visited: string[]
    visible: string[]
  }
  terrain: {
    borderOceans: HexConfigLookup
    chasm: HexConfigLookup
    forest: HexConfigLookup
    lava: HexConfigLookup
    rockyTerrain: HexConfigLookup
    sand: HexConfigLookup
    tundra: HexConfigLookup
    water: HexConfigLookup
    weird: HexConfigLookup
    all: HexConfigLookup
  }
  meta: {
    showFeature: string[]
    visibleWater: string[]
    fogless: string[]
  }
  locations: {
    pointOfInterest: HexConfigLookup
    restStop: HexConfigLookup
    tomb: HexConfigLookup
    towers: HexConfigLookup
    all: HexConfigLookup
  }
}

export const defaultMapDataState: MapDataState = {
  players: {
    current: PlayerCurrentHex,
    visible: [
      ...VisibleWaterList,
      ...Object.keys(BorderOceans),
      ...Object.keys(Tombs),
      ...PlayerVisitedHexes.flatMap(findNearbyKeysFactory(Object.keys(Towers))),
    ],
    visited: PlayerVisitedHexes,
  },
  locations: {
    pointOfInterest: PointsOfInterest,
    restStop: RestStops,
    tomb: Tombs,
    towers: Towers,
    all: { ...PointsOfInterest, ...RestStops, ...Tombs, ...Towers },
  },
  meta: {
    showFeature: [...Object.keys(Tombs)],
    visibleWater: VisibleWaterList,
    fogless: [...PlayerVisitedHexes, ...VisibleWaterList],
  },
  terrain: {
    borderOceans: BorderOceans,
    chasm: Chasm,
    forest: Forest,
    lava: Lava,
    rockyTerrain: RockyTerrain,
    sand: Sand,
    tundra: Tundra,
    water: Water,
    weird: Weird,
    all: {
      ...BorderOceans,
      ...Chasm,
      ...Forest,
      ...Lava,
      ...RockyTerrain,
      ...Sand,
      ...Tundra,
      ...Water,
      ...Weird,
    },
  },
}

export const rawGridData = {
  hexOptions: {
    size: 17,
    offset: 1,
  },
  gridOptions: {
    width: 22,
    height: 28,
  },
}

export const rawMapData = [
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["1", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["2", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["3", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["4", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["5", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["6", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["7", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["8", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["9", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["10", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["11", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["12", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["13", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["14", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["15", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["16", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["17", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["18", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["19", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["20", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "0"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "1"],
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "weird",
    marker: "tomb",
    coords: ["1", "1"],
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    marker: "rest_stop",
    coords: ["2", "1"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["3", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["4", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["7", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["9", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["10", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["11", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["12", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["13", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["15", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["16", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["17", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["18", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["19", "1"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["20", "1"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "1"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["1", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["2", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["3", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["4", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["7", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["9", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["10", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["11", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["14", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["15", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["16", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["17", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["18", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "2"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["20", "2"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "2"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["1", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["2", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["4", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["5", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["9", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["10", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["11", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["13", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["14", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["15", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["16", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["17", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "3"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "3"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "3"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["1", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["2", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "towers",
    coords: ["3", "4"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["4", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["5", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["7", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["9", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["10", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["11", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["12", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["13", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["14", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["15", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["16", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["17", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "4"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "4"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "4"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["1", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["2", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["3", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["4", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["5", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["9", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["10", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["11", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["13", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["14", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["15", "5"],
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "tundra",
    marker: "tomb",
    coords: ["16", "5"],
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["17", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["19", "5"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "5"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "5"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["1", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["2", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["4", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["7", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["9", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["10", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["11", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["12", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["13", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["14", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "rest_stop",
    coords: ["15", "6"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["16", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["17", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["19", "6"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["20", "6"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "6"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["1", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["2", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["4", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["5", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["8", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["9", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["10", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["11", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["12", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["13", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["14", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["15", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["16", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["17", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["19", "7"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "7"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "7"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["1", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["2", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["4", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["12", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["14", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["16", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "towers",
    coords: ["17", "8"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "8"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "8"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "8"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["1", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["2", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["4", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["5", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["12", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["15", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["16", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["17", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["18", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "9"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "9"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "9"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["1", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["2", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["3", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["4", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    coords: ["5", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "towers",
    coords: ["9", "10"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "rest_stop",
    coords: ["10", "10"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["12", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["16", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["17", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["18", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "10"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "10"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "10"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "rest_stop",
    coords: ["1", "11"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "tundra",
    marker: "tomb",
    coords: ["2", "11"],
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "towers",
    coords: ["3", "11"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["4", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["5", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["6", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["7", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["9", "11"],
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "rocky_terrain",
    marker: "tomb",
    coords: ["10", "11"],
    name: "The Dying God",
    description: ["According to the natives, a God lays here dying."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["11", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["12", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["13", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["16", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["17", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["18", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["19", "11"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "11"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "11"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["1", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["2", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["3", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["4", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["5", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["6", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["7", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["9", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["10", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["12", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["16", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["17", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    marker: "rest_stop",
    coords: ["18", "12"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["19", "12"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "12"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "12"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["1", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["2", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    coords: ["4", "13"],
    name: "A Rugged Sinner",
    description: [
      "Fenrik knows very little about this, but believes it may help you get to the western tomb.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["12", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["16", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["17", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["18", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["19", "13"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "13"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "13"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["1", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["2", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    coords: ["4", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    coords: ["7", "14"],
    name: "Observation Post",
    description: [
      "The Sunny-side have been using this to investigate a strange new phenomena in the great rift.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["9", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["11", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "towers",
    coords: ["14", "14"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["16", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["17", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["18", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "14"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "14"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "14"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["1", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["2", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["3", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["4", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    coords: ["5", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["11", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["16", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["17", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["18", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["19", "15"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["20", "15"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "15"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "16"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["1", "16"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["2", "16"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["3", "16"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["4", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["5", "16"],
    name: "The Infinite Hive",
    description: ["A bizarre, non-euclidean maze full of sentient squirrels"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["6", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["7", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["10", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["11", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["13", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["15", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["16", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "16"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["20", "16"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "16"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["1", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["3", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    coords: ["6", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["8", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["11", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["12", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["13", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["15", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "17"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["20", "17"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "17"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["1", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["3", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    coords: ["6", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["8", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["10", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["11", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["12", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["13", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["14", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["15", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "18"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["20", "18"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "18"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["1", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["3", "19"],
    name: "Forest",
    description: ["A Dense forest of thick trees"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["6", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    coords: ["7", "19"],
    name: "Stonework Graveyard",
    description: ["A graveyard made of stone"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["8", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["11", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["12", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["13", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "19"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["20", "19"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "19"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["1", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["3", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    coords: ["6", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    coords: ["7", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    coords: ["8", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "chasm",
    coords: ["9", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["10", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    marker: "points_of_interest",
    coords: ["11", "20"],
    name: "The Clam",
    description: ["A Giant, eldritch clam waits at the bottom of a whirlpool."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    marker: "tomb",
    coords: ["12", "20"],
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    marker: "rest_stop",
    coords: ["13", "20"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["19", "20"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["20", "20"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "20"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["1", "21"],
    name: "Forest",
    description: ["A Dense forest of thick trees"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["3", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    coords: ["5", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["6", "21"],
    name: "Curious Sculpture",
    description: [
      "A curious sculpture depicts two large stone constructs at a forge.  ",
      "It seems to have a place for a large stone orb.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["7", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["8", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["9", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["11", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["12", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["13", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["16", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "21"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["20", "21"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "21"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["1", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    coords: ["3", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    coords: ["4", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["6", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    marker: "points_of_interest",
    coords: ["9", "22"],
    name: "Sand",
    description: [
      "Warm sand covers the ground in all direction, with only the toughest surviving.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["10", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["11", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    marker: "points_of_interest",
    coords: ["12", "22"],
    name: "Deep Water",
    description: ["Who knows what secrets the Water of Beth'El provides?"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["13", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["16", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "22"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["20", "22"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "22"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["1", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["2", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "towers",
    coords: ["3", "23"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["6", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["7", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["8", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["9", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["10", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["12", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["13", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    marker: "towers",
    coords: ["15", "23"],
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["16", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["18", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["19", "23"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["20", "23"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "23"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["1", "24"],
    name: "Beirut's Flock",
    description: [
      "The Party-loving former host of divine assistants of Beirut call this place home.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["2", "24"],
    name: "Dude's Cage",
    description: [
      "Dude, the Kenku, transforms into a demonic beast when let out of his cage.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["3", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["5", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["6", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["7", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["8", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["9", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["10", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["11", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["12", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["13", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["15", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["18", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["19", "24"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["20", "24"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "24"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "25"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["1", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    coords: ["2", "25"],
    name: "Mursha's",
    description: [
      "A tavern run and operated by the divine Orc Bartender, Mursha",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "tomb",
    coords: ["3", "25"],
    name: "Tomb of Beirut",
    description: ["Final resting place of Beirut, also known as Bier'Pohn."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["4", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    coords: ["6", "25"],
    name: "Dry and Rocky",
    description: ["This area is humid and dry, with sparse plant life."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["7", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["8", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["9", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["10", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["11", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["12", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["13", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    coords: ["14", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["15", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["17", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["18", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["19", "25"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["20", "25"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "25"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "26"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["1", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "rest_stop",
    coords: ["2", "26"],
    name: "The Fallen Tree Encampment",
    description: [
      "An established camp and rest site on the isle of Beth'el.",
      "Home to a felled tree, whose bright orange sap heals travelers to the island.",
      "The party first camped here after their arrival.",
    ],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["3", "26"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["4", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    coords: ["5", "26"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["6", "26"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["7", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["8", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["9", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["10", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["11", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["12", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    coords: ["13", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    coords: ["14", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["15", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    coords: ["16", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["17", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    coords: ["18", "26"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "rest_stop",
    coords: ["19", "26"],
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    coords: ["20", "26"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "26"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["0", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["1", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["2", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["3", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["4", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["5", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["6", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["7", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["8", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["9", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["10", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["11", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["12", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["13", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["14", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["15", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["16", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["17", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["18", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["19", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["20", "27"],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    coords: ["21", "27"],
  },
]
