import {
  PlayerCurrentHex,
  PlayerVisitedHexes,
} from "../MapData/PlayerDataLists"
import {
  RockyTerrain,
  Chasm,
  Lava,
  Tundra,
  Water,
  Weird,
  Forest,
  Sand,
  VisibleWaterList,
  BorderOceans,
} from "../MapData/Terrain"
import {
  PointsOfInterest,
  RestStops,
  Towers,
  Tombs,
} from "../MapData/Locations"
import { findNearbyKeysFactory } from "../utils/findNearbyKeysFactory"
import { HexConfigLookup } from "../types"

export type MapDataState = {
  players: {
    current: string
    visited: string[]
    visible: string[]
  }
  terrain: {
    borderOceans: HexConfigLookup
    chasm: HexConfigLookup
    forest: HexConfigLookup
    lava: HexConfigLookup
    rockyTerrain: HexConfigLookup
    sand: HexConfigLookup
    tundra: HexConfigLookup
    water: HexConfigLookup
    weird: HexConfigLookup
    all: HexConfigLookup
  }
  meta: {
    showFeature: string[]
    visibleWater: string[]
    fogless: string[]
  }
  locations: {
    pointOfInterest: HexConfigLookup
    restStop: HexConfigLookup
    tomb: HexConfigLookup
    towers: HexConfigLookup
    all: HexConfigLookup
  }
}

export const defaultMapDataState: MapDataState = {
  players: {
    current: PlayerCurrentHex,
    visible: [
      ...VisibleWaterList,
      ...Object.keys(BorderOceans),
      ...Object.keys(Tombs),
      ...PlayerVisitedHexes.flatMap(findNearbyKeysFactory(Object.keys(Towers))),
    ],
    visited: PlayerVisitedHexes,
  },
  locations: {
    pointOfInterest: PointsOfInterest,
    restStop: RestStops,
    tomb: Tombs,
    towers: Towers,
    all: { ...PointsOfInterest, ...RestStops, ...Tombs, ...Towers },
  },
  meta: {
    showFeature: [...Object.keys(Tombs)],
    visibleWater: VisibleWaterList,
    fogless: [...PlayerVisitedHexes, ...VisibleWaterList],
  },
  terrain: {
    borderOceans: BorderOceans,
    chasm: Chasm,
    forest: Forest,
    lava: Lava,
    rockyTerrain: RockyTerrain,
    sand: Sand,
    tundra: Tundra,
    water: Water,
    weird: Weird,
    all: {
      ...BorderOceans,
      ...Chasm,
      ...Forest,
      ...Lava,
      ...RockyTerrain,
      ...Sand,
      ...Tundra,
      ...Water,
      ...Weird,
    },
  },
}

export const rawMapData = [
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "1-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "2-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "3-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "4-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "5-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "6-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "7-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "8-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "9-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "10-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "11-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "12-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "13-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "14-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "15-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "16-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "17-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "18-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "19-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "20-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-0",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-1",
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "weird",
    marker: "tomb",
    key: "1-1",
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    marker: "rest_stop",
    key: "2-1",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "3-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "4-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "7-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "9-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "10-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "11-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "12-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "13-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "15-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "16-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "17-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "18-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "19-1",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "20-1",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-1",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "1-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "2-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "3-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "4-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "7-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "9-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "10-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "11-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "14-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "15-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "16-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "17-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "18-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-2",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "20-2",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-2",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "1-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "2-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "4-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "5-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "9-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "10-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "11-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "13-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "14-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "15-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "16-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "17-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-3",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-3",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-3",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "1-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "2-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "towers",
    key: "3-4",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "4-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "5-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "7-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "9-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "10-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "11-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "12-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "13-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "14-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "15-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "16-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "17-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-4",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-4",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-4",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "1-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "2-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "3-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "4-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "5-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "9-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "10-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "11-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "13-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "14-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "15-5",
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "tundra",
    marker: "tomb",
    key: "16-5",
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "17-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "19-5",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-5",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-5",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "1-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "2-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "4-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "7-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "9-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "10-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "11-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "12-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "13-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "14-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "rest_stop",
    key: "15-6",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "16-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "17-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "19-6",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "20-6",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-6",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "1-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "2-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "4-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "5-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "8-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "9-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "10-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "11-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "12-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "13-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "14-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "15-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "16-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "17-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "19-7",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-7",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-7",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "1-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "2-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "4-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "12-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "14-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "16-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "towers",
    key: "17-8",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-8",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-8",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-8",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "1-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "2-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "4-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "5-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "12-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "15-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "16-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "17-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "18-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-9",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-9",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-9",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "1-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "2-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "3-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "4-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "lava",
    key: "5-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "towers",
    key: "9-10",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "rest_stop",
    key: "10-10",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "12-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "16-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "17-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "18-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-10",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-10",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-10",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "rest_stop",
    key: "1-11",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "tundra",
    marker: "tomb",
    key: "2-11",
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    marker: "towers",
    key: "3-11",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "4-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "5-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "6-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "7-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "9-11",
  },
  {
    borderVisible: false,
    showFeature: true,
    visible: false,
    terrain: "rocky_terrain",
    marker: "tomb",
    key: "10-11",
    name: "The Dying God",
    description: ["According to the natives, a God lays here dying."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "11-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "12-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "13-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "16-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "17-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "18-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "19-11",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-11",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-11",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "1-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "2-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "3-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "4-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "5-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "6-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "7-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "9-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "10-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "12-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "16-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "17-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    marker: "rest_stop",
    key: "18-12",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "19-12",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-12",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-12",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "1-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "2-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    key: "4-13",
    name: "A Rugged Sinner",
    description: [
      "Fenrik knows very little about this, but believes it may help you get to the western tomb.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "12-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "16-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "17-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "18-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "19-13",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-13",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-13",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "1-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "2-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    key: "4-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    key: "7-14",
    name: "Observation Post",
    description: [
      "The Sunny-side have been using this to investigate a strange new phenomena in the great rift.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "9-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "11-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "towers",
    key: "14-14",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "16-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "17-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "18-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-14",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-14",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-14",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "1-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "2-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "3-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "4-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    key: "5-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "11-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "16-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "17-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "18-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "19-15",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "20-15",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-15",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-16",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "1-16",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "2-16",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "3-16",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "4-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    key: "5-16",
    name: "The Infinite Hive",
    description: ["A bizarre, non-euclidean maze full of sentient squirrels"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "6-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "7-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "10-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "11-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "13-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "15-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "16-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-16",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "20-16",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-16",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "1-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "3-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    key: "6-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "8-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "11-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "12-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "13-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "15-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-17",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "20-17",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-17",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "1-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "3-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    key: "6-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "8-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "10-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "11-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "12-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "13-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "14-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "15-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-18",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "20-18",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-18",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "1-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "points_of_interest",
    key: "3-19",
    name: "Forest",
    description: ["A Dense forest of thick trees"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "6-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    key: "7-19",
    name: "Stonework Graveyard",
    description: ["A graveyard made of stone"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "8-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "11-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "12-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "13-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-19",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "20-19",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-19",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "1-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "3-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    key: "6-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    key: "7-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "rocky_terrain",
    key: "8-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "chasm",
    key: "9-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "10-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    marker: "points_of_interest",
    key: "11-20",
    name: "The Clam",
    description: ["A Giant, eldritch clam waits at the bottom of a whirlpool."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    marker: "tomb",
    key: "12-20",
    name: "A Fallen God's Tomb",
    description: ["A God lays here in rest."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "water",
    marker: "rest_stop",
    key: "13-20",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "19-20",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "20-20",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-20",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "points_of_interest",
    key: "1-21",
    name: "Forest",
    description: ["A Dense forest of thick trees"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "3-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    key: "5-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    key: "6-21",
    name: "Curious Sculpture",
    description: [
      "A curious sculpture depicts two large stone constructs at a forge.  ",
      "It seems to have a place for a large stone orb.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "7-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "8-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "9-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "11-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "12-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "13-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "16-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-21",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "20-21",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-21",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "1-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    key: "3-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    key: "4-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "6-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    marker: "points_of_interest",
    key: "9-22",
    name: "Sand",
    description: [
      "Warm sand covers the ground in all direction, with only the toughest surviving.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "10-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "11-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    marker: "points_of_interest",
    key: "12-22",
    name: "Deep Water",
    description: ["Who knows what secrets the Water of Beth'El provides?"],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "13-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "16-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-22",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "20-22",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-22",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "1-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "2-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "towers",
    key: "3-23",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "6-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "7-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "8-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "9-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "10-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "12-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "13-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    marker: "towers",
    key: "15-23",
    name: "Observation Tower",
    description: [
      "This tower reaches high above the terrain, allowing you to see a greater distance away.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "16-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "18-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "19-23",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "20-23",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-23",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    key: "1-24",
    name: "Beirut's Flock",
    description: [
      "The Party-loving former host of divine assistants of Beirut call this place home.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    key: "2-24",
    name: "Dude's Cage",
    description: [
      "Dude, the Kenku, transforms into a demonic beast when let out of his cage.",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "3-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "5-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "6-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "7-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "8-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "9-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "10-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "11-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "12-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "13-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "15-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "18-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "19-24",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "20-24",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-24",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-25",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "1-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "points_of_interest",
    key: "2-25",
    name: "Mursha's",
    description: [
      "A tavern run and operated by the divine Orc Bartender, Mursha",
    ],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "tomb",
    key: "3-25",
    name: "Tomb of Beirut",
    description: ["Final resting place of Beirut, also known as Bier'Pohn."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "4-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    marker: "points_of_interest",
    key: "6-25",
    name: "Dry and Rocky",
    description: ["This area is humid and dry, with sparse plant life."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "7-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "8-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "9-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "10-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "11-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "12-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "13-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "chasm",
    key: "14-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "15-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "17-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "18-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "19-25",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "20-25",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-25",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-26",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "1-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: true,
    terrain: "forest",
    marker: "rest_stop",
    key: "2-26",
    name: "The Fallen Tree Encampment",
    description: [
      "An established camp and rest site on the isle of Beth'el.",
      "Home to a felled tree, whose bright orange sap heals travelers to the island.",
      "The party first camped here after their arrival.",
    ],
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "3-26",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "4-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "rocky_terrain",
    key: "5-26",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "6-26",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "7-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "8-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "9-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "10-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "11-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "12-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "tundra",
    key: "13-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "water",
    key: "14-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "15-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "sand",
    key: "16-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "17-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    key: "18-26",
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "forest",
    marker: "rest_stop",
    key: "19-26",
    name: "A Felled Tree",
    description: ["It seems to be leaking Sap."],
  },
  {
    borderVisible: false,
    showFeature: false,
    visible: false,
    terrain: "weird",
    key: "20-26",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-26",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "0-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "1-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "2-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "3-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "4-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "5-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "6-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "7-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "8-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "9-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "10-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "11-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "12-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "13-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "14-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "15-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "16-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "17-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "18-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "19-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "20-27",
  },
  {
    borderVisible: true,
    showFeature: false,
    visible: true,
    terrain: "water",
    key: "21-27",
  },
]
